name: ajouthon_2023
description: A new Flutter project.

publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  geolocator: ^10.1.0
  get: ^4.6.6
  google_maps_flutter: ^2.5.0
  http: ^1.1.0
  label_marker: ^1.0.1
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: SUIT
      fonts:
        - asset: assets/font/SUIT-Thin.otf
          weight: 100
        - asset: assets/font/SUIT-ExtraLight.otf
          weight: 200
        - asset: assets/font/SUIT-Light.otf
          weight: 300
        - asset: assets/font/SUIT-Regular.otf
          weight: 400
        - asset: assets/font/SUIT-Medium.otf
          weight: 500
        - asset: assets/font/SUIT-SemiBold.otf
          weight: 600
        - asset: assets/font/SUIT-Bold.otf
          weight: 700
        - asset: assets/font/SUIT-Heavy.otf
          weight: 800
        - asset: assets/font/SUIT-ExtraBold.otf
          weight: 900
